import Mathlib

-- Precondition auxiliary definitions
/-- The sum of the squares of the digits of a natural number. -/
def sumOfSquares : Nat → Nat
  | 0 => 0
  | n@(Nat.succ _) => (n % 10) ^ 2 + sumOfSquares (n / 10)

/-- The set of numbers seen so far in the happy number sequence. -/
def HappyNumSeq (seen : List Nat) (current : Nat) : Prop :=
  current = 1 ∨ current ∈ seen

/-- The full sequence of numbers generated by repeatedly applying sumOfSquares,
    starting from `n`, until it reaches 1 or a cycle is detected. -/
inductive HappySequence : List Nat → Nat → Prop
  /-- Base case: the sequence is complete if the current number is 1. -/
  | done (seq : List Nat) : HappySequence (1 :: seq) 1
  /-- Recursive case: if the current number is not 1 and not in the sequence,
      add it to the sequence and continue. -/
  | step {seq : List Nat} {n : Nat} (h : n ≠ 1 ∧ n ∉ seq) :
      HappySequence (n :: seq) (sumOfSquares n) → HappySequence (n :: seq) n

/-- A number `n` is happy if there exists a sequence starting from `n`
    that eventually reaches 1. -/
def isHappyNum (n : Nat) : Prop :=
  ∃ seq : List Nat, HappySequence seq n ∧ seq.getLast? = some 1

-- Precondition definitions
@[reducible, simp]
def isHappy_precond (n : Nat) : Prop :=
  -- !benchmark @start precond
  n ≥ 1
  -- !benchmark @end precond


-- Code auxiliary definitions
/-- Helper function to compute the sum of squares of digits iteratively. -/
def sumOfSquaresAux (n : Nat) : Nat :=
  let digits := Nat.toDigits 10 n
  List.foldl (fun acc d => acc + (d : Nat) ^ 2) 0 (digits.map (·.toNat))

-- Main function definitions
def isHappy (n : Nat) (h_precond : isHappy_precond (n)) : Bool :=
  -- !benchmark @start code
  let rec loop (current : Nat) (seen : List Nat) : Bool :=
    if current == 1 then
      true
    else if seen.contains current then
      false
    else
      let next := sumOfSquaresAux current
      loop next (current :: seen)
  decreasing_by
    sorry
  loop n []
  -- !benchmark @end code


-- Postcondition definitions
@[reducible, simp]
def isHappy_postcond (n : Nat) (result: Bool) (h_precond : isHappy_precond (n)) : Prop :=
  -- !benchmark @start postcond
  result = true ↔ isHappyNum n
  -- !benchmark @end postcond


-- Proof content
theorem isHappy_postcond_satisfied (n: Nat) (h_precond : isHappy_precond (n)) :
    isHappy_postcond (n) (isHappy (n) h_precond) h_precond := by
  -- !benchmark @start proof
  sorry
  -- !benchmark @end proof